---
 - name: Install httpd
   yum:
    name: httpd
    state: installed
   when: ansible_os_family == "RedHat"
   notify: start the httpd service

 - name: copy the file
   copy:
     src: /home/ansadmin/index.html
     dest: /var/www/html
     mode: '0777'
