---
- name: my playbook
  hosts: webserver
  become: true
  tasks:
    - name: copy the file
      copy:
        src: /etc/ansible/sample
        dest: /home/ansadmin
        mode: 0600
        owner: demon
