---
- name: My playbook
  hosts: webserver
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Install apache2 package
      yum:
        name: apache2
        state: installed
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name:
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html
