---
- name: my playbook
  hosts: webserver
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    notify: start the httpd service
        
  handlers:    
  - name: start the httpd service
    service:
      name: httpd
      state: started
